workflows:
  android-workflow:
    name: Android Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: Build Android release
        script: gradlew assembleRelease
artifacts:
  - app/build/outputs/**/*.apk